title: "[Proposal] "
labels: ["HGVS Nomenclature Change Proposal"]
body:
  - type: textarea
    id: background
    attributes:
      label: Background
      description: "What is the issue this proposal is addressing?"
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Please describe specific proposed change(s) for consideration.
        If you do not have a specific solution in mind, leave this field blank.
