title: "[Proposal] "
labels: ["HGVS Nomenclature Change Proposal"]
body:
  - type: markdown
    attributes:
      value: |
        HGVS Nomenclature Change Proposal
  - type: textarea
    id: background
    attributes:
      label: Background
      description: "What is the issue this proposal is addressing?"
    validations:
      required: true
